### ISSUE TITLE
support for user terminated search process

### ISSUE THREAD

**Issue by dirkschumacher** [dirkschumacher/ompr.roi#6]
If you e.g. set a timelimit for glpk, the result is infeasible with no solution if even a (non-optimal) solution was found during the search process.

**Comment by dirkschumacher** [comment]
Testcase:
```R
set.seed(42)
max_bins <- 10
bin_size <- 3
n <- 10
weights <- runif(n, max = bin_size)
model <- MIPModel() %>%
  add_variable(y[i], i = 1:max_bins, type = "binary") %>%
  add_variable(x[i, j], i = 1:max_bins, j = 1:n, type = "binary") %>%
  set_objective(sum_expr(y[i], i = 1:max_bins), "min") %>%
  add_constraint(sum_expr(weights[j] * x[i, j], j = 1:n) <= y[i] * bin_size, i = 1:max_bins) %>%
  add_constraint(sum_expr(x[i, j], i = 1:max_bins) == 1, j = 1:n)
result <- solve_model(model, with_ROI("glpk",
                                      control = list(tm_limit = 1000,
                                                     presolve = FALSE, verbose = TRUE)))
expect_equal("userlimit", ompr::solver_status(result))
expect_true(ompr::objective_value(result) > 0)
```

It seems to be a problem with `ROI.plugin.glpk`

**Comment by dirkschumacher** [comment]
So, I looked at it again. ROI now returns a user terminated solution, but it always marks it as infeasible. 
Of course I could always return that solution, but the problem is, that in the in case of an actual infeasible solution, ROI still returns a solution and an objective value (which are infeasible). It thus seems like, it is impossible to decide, if a returned solution is actual feasible or not (unless it is optimal).

I will contact the ROI authors.

This also affects the issue here: https://github.com/dirkschumacher/ompr/issues/163
cc @ralphasher, @rickyars

**Comment by ralphasher** [comment]
Thanks in advance for contacting the ROI authors.   I really like your package (way better than Rsymphony for user friendliness!) but especially when I have larger MIPs I want to be able to put on a gap limit.  Also, the issue was occurring when I only passed along verbosity as an argument to Symphony, even without a gap limit argument.

Ralph

**Comment by rickyars** [comment]
When I run the above code I still get nothing returned when I ask for the solution. 

```
> get_solution(result, x[i,j])
[1] variable i        j        value   
<0 rows> (or 0-length row.names)
```

In my experience, the ROI guys are very slow to respond. Good luck and please let us know how it goes. I'm really depending on this working for some of my work.

**Comment by dirkschumacher** [comment]
As of now they do not want to add additional status codes. But you could use `as_ROI_model ` to export the model to a ROI `OP` class and then solve it. Then you get at least the solution vector.

**Comment by rickyars** [comment]
Can you explain how that would work? I can't even find the function `as_ROI_model`.

**Comment by dirkschumacher** [comment]
It is currently just in the master branch.

You can take an `ompr` model and convert it to a ROI model: `rmodel <-
 ompr.roi::as_ROI_model(model)`. Then you can solve it with ROI `res <- ROI::ROI_solve(rmodel, "glpk")`

**Comment by rickyars** [comment]
Damn. For reasons I don't want to get in to, if it's not on CRAN then I can't run it.

**Comment by dirkschumacher** [comment]
Ok. It will be soon

**Comment by rickyars** [comment]
Weird. This doesn't work - it returns all NA values:
```
ROI::solution(res)
```

But this does work:
```
res$solution
```

**Comment by dirkschumacher** [comment]
It might be that `ROI::solution` only returns a non NA vector when the solution is optimal.

**Comment by utkucivelek** [comment]
Thanks for the package. I have 5D, 4D, and 3D variables in my model. That's why using "as_ROI_model" and getting the solution vector creates new problems. Is there a method like "to_ROI_solution," which inverses the array generation?

**Comment by devu123** [comment]
getting the solution with res$solution works, but when you convert the `ompr` model to a `ROI` model, the shape of your variables is lost (in case you have a variable x[i, j])

It would be helpful to have a way to convert the solution back to the original shape of the `ompr` model variables. 

The solution status when you solve an `OMPR` model with symphony solver and option `first_feasible = T` is still infeasible but the solution returns the same objective value and solution as when you convert the `OMPR` model to a `ROI` model and solve it, with the solution of the `ROI` model's status being `TM_FOUND_FIRST_FEASIBLE`

**Comment by dirkschumacher** [comment]
With PR #24, we can easily access the raw solver information and grab the solver specific code from there. ROI still returns `infeasible` though.

``` r
library(ompr)
library(ompr.roi)
library(ROI.plugin.glpk)
set.seed(42)
max_bins <- 10
bin_size <- 3
n <- 10
weights <- runif(n, max = bin_size)
model <- MIPModel() |>
  add_variable(y[i], i = 1:max_bins, type = "binary") |>
  add_variable(x[i, j], i = 1:max_bins, j = 1:n, type = "binary") |>
  set_objective(sum_expr(y[i], i = 1:max_bins), "min") |>
  add_constraint(sum_expr(weights[j] * x[i, j], j = 1:n) <= y[i] * bin_size, i = 1:max_bins) |>
  add_constraint(sum_expr(x[i, j], i = 1:max_bins) == 1, j = 1:n)
result <- solve_model(model, with_ROI("glpk",
                                      control = list(tm_limit = 1000,
                                                     presolve = FALSE, verbose = TRUE)))
#> <SOLVER MSG>  ----
#> GLPK Simplex Optimizer, v4.65
#> 20 rows, 110 columns, 210 non-zeros
#>       0: obj =   0.000000000e+00 inf =   1.000e+01 (10)
#>      32: obj =   6.362622072e+00 inf =   0.000e+00 (0)
#> *    36: obj =   6.362622072e+00 inf =   0.000e+00 (0)
#> OPTIMAL LP SOLUTION FOUND
#> GLPK Integer Optimizer, v4.65
#> 20 rows, 110 columns, 210 non-zeros
#> 110 integer variables, all of which are binary
#> Integer optimization begins...
#> Long-step dual simplex will be used
#> +    36: mip =     not found yet >=              -inf        (1; 0)
#> Solution found by heuristic: 8
#> + 65771: mip =   8.000000000e+00 >=   7.000000000e+00  12.5% (1380; 25220)
#> TIME LIMIT EXCEEDED; SEARCH TERMINATED
#> <!SOLVER MSG> ----
result$additional_solver_output$ROI$status
#> $code
#> [1] 1
#> 
#> $msg
#>   solver glpk
#>     code 2
#>   symbol GLP_FEAS
#>  message Solution is feasible.
#> roi_code 1
result$additional_solver_output$ROI$status$msg$symbol
#> [1] "GLP_FEAS"
```

<sup>Created on 2022-01-19 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>
