### ISSUE TITLE
bounds on binary variables are ignored in ROI

### ISSUE THREAD

**Issue by dirkschumacher** [dirkschumacher/ompr.roi#7]
As far as I can see it this is a bug in ROI (just reported it). 
Until this is fixed, you need to use integer variables with bounds 0/1 instead of binary variables if you want to set custom bounds.

https://gist.github.com/dirkschumacher/4c0d8f1681579e828a6fc170759781e8

**Comment by dirkschumacher** [comment]
Seems to be a `Rglpk` problem.

**Comment by ryanjoneil** [comment]
I ran into similar issues with bounds on binary variables in [RAMS](https://github.com/ryanjoneil/rams). Certain versions of GLPK didn't respect setting an upper bound or 0 or a lower bound of 1, but would work with x <= 0 and x >= 1 constraints. Try upgrading to GLPK 4.6. That solved the issue for me.
